# Generated by Django 3.2.25 on 2025-07-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='操作类型')),
                ('repository', models.CharField(max_length=100, verbose_name='仓库')),
                ('user', models.CharField(max_length=100, verbose_name='用户')),
                ('detail', models.TextField(verbose_name='详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': 'Git操作日志',
                'verbose_name_plural': 'Git操作日志',
            },
        ),
    ]
